### ISSUE TITLE
problem running npm -g install yuidocs

### ISSUE THREAD

**Issue by pamwebber** [pamwebber/pamsRepository#1]
#

**Comment by pamwebber** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'yuidocjs' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\teerip01\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\teerip01\AppData\Roaming\npm\package.json
6 silly cache add args [ 'yuidocjs', null ]
7 verbose cache add spec yuidocjs
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'yuidocjs',
8 silly cache add   scope: null,
8 silly cache add   name: 'yuidocjs',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed yuidocjs@latest
10 verbose addNamed "latest" is being treated as a dist-tag for yuidocjs
11 info addNameTag [ 'yuidocjs', 'latest' ]
12 silly mapToRegistry name yuidocjs
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'yuidocjs',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'yuidocjs',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/yuidocjs
17 verbose addNameTag registry:https://registry.npmjs.org/yuidocjs not in flight; fetching
18 verbose request uri https://registry.npmjs.org/yuidocjs
19 verbose request no auth needed
20 info attempt registry request try #1 at 6:49:10 PM
21 verbose request id 684bef7d828a9693
22 http request GET https://registry.npmjs.org/yuidocjs
23 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
24 info attempt registry request try #2 at 6:49:20 PM
25 http request GET https://registry.npmjs.org/yuidocjs
26 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
27 info attempt registry request try #3 at 6:50:20 PM
28 http request GET https://registry.npmjs.org/yuidocjs
29 verbose stack Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
29 verbose stack
29 verbose stack     at exports._errnoException (util.js:873:11)
29 verbose stack     at WriteWrap.afterWrite (net.js:785:14)
30 verbose cwd C:\Users\teerip01
31 error Windows_NT 6.1.7601
32 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "-g" "install" "yuidocjs"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code EPROTO
36 error errno EPROTO
37 error syscall write
38 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:
39 error If you need help, you may report this error at:
39 error     https://github.com/npm/npm/issues
40 verbose exit [ 1, true ]
